ElearningApp/Controllers/InstructorController.cs
using ElearningApp.Filters;
using ElearningApp.Models;
using ElearningApp.Models.Business;
using ElearningApp.Models.Entity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElearningApp.Controllers
{
    [AppAuthenticate]
    public class InstructorController : Controller
    {
        // GET: Instructor
        [AppAuthorize]
        [AppLog]
        public ActionResult Index()
        {
            return View();
        }
        [AppAuthorize]
        [AppLog]
        public ActionResult Create()
        {
            return View();
        }
        [AppAuthorize]
        [AppLog]
        public ActionResult Edit(string id)
        {
            int l_id = Convert.ToInt32(Helpers.GetBase64Decode(id));
            Bus_List l_list = new Bus_List();
            Instructor_Entity l_model = null;
            var l_instructor = l_list.RetrieveInstructor(l_id);
            bool l_noData = l_instructor.Rows.Count == 0;
            if (!l_noData)
            {
                l_model = new Instructor_Entity
                {
                    Id = l_id,
                    Type = l_instructor.Rows[0]["Tipo"].ToString(),
                    PersonId = Convert.ToDecimal(l_instructor.Rows[0]["Codi_Pers"]),
                    Status = l_instructor.Rows[0]["Estado"].ToString(),
                    LastName1 = l_instructor.Rows[0]["Ap_Paterno"].ToString(),
                    LastName2 = l_instructor.Rows[0]["Ap_Materno"].ToString(),
                    FirstName = l_instructor.Rows[0]["Nombres"].ToString(),
                    DocumentTypeId = Convert.ToDecimal(l_instructor.Rows[0]["Codi_Tdoc"]),
                    DocumentNumber = l_instructor.Rows[0]["Nro_Doc"].ToString(),
                    Email = l_instructor.Rows[0]["Email"].ToString(),
                    PersonType = l_instructor.Rows[0]["Persona_Tipo"].ToString()
                };
            }

            Helpers.ClearDataTable(l_instructor);
            l_list = null;

            ViewBag.NGon.Model = l_model;

            if (l_noData)
            {
                return View("NotFound");
            }
            else
            {
                return View(l_model);
            }
        }
        [HttpPost]
        public ActionResult Create(Instructor_Entity p_Entity)
        {
            Bus_Crud l_crud;
            try
            {
                l_crud = new Bus_Crud();
                p_Entity.Id = 0;
                p_Entity.Username = SessionHelpers.GetUsername();
                p_Entity.IPAddress = SessionHelpers.GetIPAddress();
                return Helpers.GetMessageCrud(l_crud.InsertUpdateInstructor(p_Entity));
            }
            catch (Exception e)
            {
                return Helpers.GetException(e);
            }
            finally
            {
                l_crud = null;
            }
        }
        [HttpPost]
        public ActionResult Edit(Instructor_Entity p_Entity)
        {
            Bus_Crud l_crud;
            try
            {
                l_crud = new Bus_Crud();
                p_Entity.Username = SessionHelpers.GetUsername();
                p_Entity.IPAddress = SessionHelpers.GetIPAddress();
                return Helpers.GetMessageCrud(l_crud.InsertUpdateInstructor(p_Entity));
            }
            catch (Exception e)
            {
                return Helpers.GetException(e);
            }
            finally
            {
                l_crud = null;
            }
        }
        [HttpPost]
        public ActionResult Delete(Instructor_Entity p_Entity)
        {
            Bus_Crud l_crud;
            try
            {
                l_crud = new Bus_Crud();
                p_Entity.Username = SessionHelpers.GetUsername();
                p_Entity.IPAddress = SessionHelpers.GetIPAddress();
                return Helpers.GetMessageCrud(l_crud.DeleteInstructor(p_Entity));
            }
            catch (Exception e)
            {
                return Helpers.GetException(e);
            }
            finally
            {
                l_crud = null;
            }
        }
        [HttpPost]
        public JsonResult GetList()
        {
            Bus_List l_list;
            List<object> l_result;
            try
            {
                l_list = new Bus_List();
                l_result = new List<object>();
                var l_records = l_list.GetInstructorList();
                foreach (DataRow row in l_records.Rows)
                {
                    l_result.Add(new List<object>
                    {
                        row["Codi_Inst"],//0
                        row["Documento"],//1
                        row["Nombre"],//2
                        row["Email"],//3
                        row["Tipo"],//4
                        row["Estado"]//5
                    });
                }

                Helpers.ClearDataTable(l_records);

                return new JsonResult()
                {
                    Data = new
                    {
                        data = l_result
                    },
                    MaxJsonLength = Int32.MaxValue,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            catch
            {
                return new JsonResult()
                {
                    Data = new
                    {
                        data = new string[0]
                    },
                    MaxJsonLength = Int32.MaxValue,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            finally
            {
                l_list = null;
                l_result = null;
            }
        }
        [HttpPost]
        public JsonResult GetPerson(int document, string number)
        {
            Bus_List l_list;
            List<object> l_result = null;
            try
            {
                l_list = new Bus_List();
                var l_records = l_list.GetPerson2Instructor(document, number);
                foreach (DataRow row in l_records.Rows)
                {
                    l_result = new List<object>
                    {
                        row["Codi_Pers"],//0
                        row["Ap_Paterno"],//1
                        row["Ap_Materno"],//2
                        row["Nombres"],//3
                        row["Email"],//4
                        row["Tipo"]//5
                    };
                }

                Helpers.ClearDataTable(l_records);

                return new JsonResult()
                {
                    Data = new
                    {
                        status = 1,
                        response = l_result
                    },
                    MaxJsonLength = Int32.MaxValue,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            catch (Exception e)
            {
                return Helpers.GetException(e);
            }
            finally
            {
                l_list = null;
                l_result = null;
            }
        }
    }
}

ElearningApp/Views/Instructor/Create.cshtml
@{
    ViewBag.title = "Instructor :: Nuevo";
    ViewBag.app_version = ElearningApp.Models.Helpers.APP_VERSION;
}
<div class="material-background ms-hero-img-elearning ms-hero-bg-app"></div>
<div class="container container-full app-container">
    <div class="app-container-breadcrumb">
        <ul class="app-breadcrumb animated fadeInRight animation-delay-5">
            <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"> </span></a></li>
            <li><a href="@Url.Action("Index", "Instructor")">Instructor</a></li>
            <li><a href="javascript:void(0)" class="active">Nuevo</a></li>
        </ul>
    </div>
    <div class="card animated slideInUp animation-delay-8">
        <div class="card-body">
            <form id="instructor_create_form" autocomplete="off" action="#" class="app-form" data-presave-rule="object" data-presave-analysis="insert">
                <h4 class="right-line right-line-white cls-1812051504">Documento</h4>
                <div class="row">
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_create_document_type"><span class="text-dark">Tipo Documento</span> <span class="text-danger">*</span></label>
                            <select id="instructor_create_document_type" class="form-control" data-live-search="true" data-dropup-auto="false" data-presave-object="Tipo Documento"></select>
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_create_document_number"><span class="text-dark">N° Documento</span> <span class="text-danger">*</span> | Máximo 30 caracteres</label>
                            <input id="instructor_create_document_number" type="text" maxlength="30" class="form-control" data-presave-object="N° Documento" />
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="app-row cls-1901151144">
                            <button id="instructor_create_retrieve" class="btn btn-raised btn-primary pull-left m-0" data-toggle="tooltip" data-placement="top" title="Recuperar">
                                <i class="glyphicon glyphicon-search m-0"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <h4 class="right-line right-line-white cls-1812051504">Datos Personales</h4>
                <div class="row">
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_create_last_name_1"><span class="text-dark">Apellido Paterno</span> <span class="text-danger">*</span> | Máximo 100 caracteres</label>
                            <input id="instructor_create_last_name_1" type="text" maxlength="100" class="form-control pointer-events-none" data-presave-object="Apellido Paterno" disabled />
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_create_last_name_2"><span class="text-dark">Apellido Materno</span> <span class="text-danger">*</span> | Máximo 100 caracteres</label>
                            <input id="instructor_create_last_name_2" type="text" maxlength="100" class="form-control pointer-events-none" data-presave-object="Apellido Materno" disabled />
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_create_first_name"><span class="text-dark">Nombre</span> <span class="text-danger">*</span> | Máximo 100 caracteres</label>
                            <input id="instructor_create_first_name" type="text" maxlength="100" class="form-control pointer-events-none" data-presave-object="Nombre" disabled />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_create_email"><span class="text-dark">Correo Electrónico</span> <span class="text-danger">*</span> | Máximo 50 caracteres</label>
                            <input id="instructor_create_email" type="text" maxlength="50" class="form-control pointer-events-none" data-presave-object="Correo Electrónico" disabled />
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_create_type"><span class="text-dark">Tipo</span></label>
                            <input id="instructor_create_type" type="text" class="form-control pointer-events-none" disabled />
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_create_status"><span class="text-dark">Activo</span></label>
                            <div class="togglebutton">
                                <label>
                                    <input id="instructor_create_status" type="checkbox" checked>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <hr class="border-dark" />
            <div class="app-row">
                <span class="small text-dark">Campo requerido (<span class="text-danger">*</span>)</span>
                @Helpers.TagHelper.buttonSave("instructor_create_save")
            </div>
        </div>
    </div>
</div>
@section styles{
    <link href="~/assets/app/app.css?v=@ViewBag.app_version" rel="stylesheet" />
    <link href="~/assets/site/site.css?v=@ViewBag.app_version" rel="stylesheet" />
}
@section scripts{
    <script src="~/assets/app/initialize.js?v=@ViewBag.app_version"></script>
    <script src="~/assets/site/instructor/create.js?v=@ViewBag.app_version"></script>
}

ElearningApp/Views/Instructor/Edit.cshtml
@model ElearningApp.Models.Entity.Instructor_Entity
@{
    ViewBag.title = "Instructor :: Editar";
    ViewBag.app_version = ElearningApp.Models.Helpers.APP_VERSION;
}
@using NGon
@Html.IncludeNGon()
<div class="material-background ms-hero-img-elearning ms-hero-bg-app"></div>
<div class="container container-full app-container">
    <div class="app-container-breadcrumb">
        <ul class="app-breadcrumb animated fadeInRight animation-delay-5">
            <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"> </span></a></li>
            <li><a href="@Url.Action("Index", "Instructor")">Instructor</a></li>
            <li><a href="javascript:void(0)" class="active">Editar</a></li>
        </ul>
    </div>
    <div class="card animated slideInUp animation-delay-8">
        <div class="card-body">
            <form id="instructor_edit_form" autocomplete="off" action="#" class="app-form" data-presave-rule="object" data-presave-analysis="insert">
                <h4 class="right-line right-line-white cls-1812051504">Documento</h4>
                <div class="row">
                    <div class="col-12 col-sm-6">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_edit_document_type"><span class="text-dark">Tipo Documento</span> <span class="text-danger">*</span></label>
                            <select id="instructor_edit_document_type" class="form-control pointer-events-none no-color-disabled" data-live-search="true" data-dropup-auto="false" data-presave-object="Tipo Documento" disabled></select>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_edit_document_number"><span class="text-dark">N° Documento</span> <span class="text-danger">*</span> | Máximo 30 caracteres</label>
                            <input id="instructor_edit_document_number" type="text" maxlength="30" class="form-control pointer-events-none no-color-disabled" data-presave-object="N° Documento" value="@Model.DocumentNumber" disabled />
                        </div>
                    </div>
                    @*<div class="col-12 col-sm-4">
                            <div class="app-row cls-1901151144">
                                <button id="instructor_edit_retrieve" class="btn btn-raised btn-primary pull-left m-0" data-toggle="tooltip" data-placement="top" title="Recuperar">
                                    <i class="glyphicon glyphicon-search m-0"></i>
                                </button>
                            </div>
                        </div>*@
                </div>
                <h4 class="right-line right-line-white cls-1812051504">Datos Personales</h4>
                <div class="row">
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_edit_last_name_1"><span class="text-dark">Apellido Paterno</span> <span class="text-danger">*</span> | Máximo 100 caracteres</label>
                            <input id="instructor_edit_last_name_1" type="text" maxlength="100" class="form-control pointer-events-none" data-presave-object="Apellido Paterno" value="@Model.LastName1" disabled />
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_edit_last_name_2"><span class="text-dark">Apellido Materno</span> <span class="text-danger">*</span> | Máximo 100 caracteres</label>
                            <input id="instructor_edit_last_name_2" type="text" maxlength="100" class="form-control pointer-events-none" data-presave-object="Apellido Materno" value="@Model.LastName2" disabled />
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_edit_first_name"><span class="text-dark">Nombre</span> <span class="text-danger">*</span> | Máximo 100 caracteres</label>
                            <input id="instructor_edit_first_name" type="text" maxlength="100" class="form-control pointer-events-none" data-presave-object="Nombre" value="@Model.FirstName" disabled />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_edit_email"><span class="text-dark">Correo Electrónico</span> <span class="text-danger">*</span> | Máximo 50 caracteres</label>
                            <input id="instructor_edit_email" type="text" maxlength="50" class="form-control pointer-events-none" data-presave-object="Correo Electrónico" value="@Model.Email" disabled />
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_edit_type"><span class="text-dark">Tipo</span></label>
                            <input id="instructor_edit_type" type="text" class="form-control pointer-events-none" value="@(Model.Type == "E" ? "Externo" : Model.Type == "I" ? "Interno" : "")" disabled />
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="instructor_edit_status"><span class="text-dark">Activo</span></label>
                            <div class="togglebutton">
                                <label>
                                    <input id="instructor_edit_status" type="checkbox" @(Model.Status == "A" ? @Html.Raw("checked") : @Html.Raw(""))>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <hr class="border-dark" />
            <div class="app-row">
                <span class="small text-dark">Campo requerido (<span class="text-danger">*</span>)</span>
                @Helpers.TagHelper.buttonSave("instructor_edit_save")
            </div>
        </div>
    </div>
</div>
@section styles{
    <link href="~/assets/app/app.css?v=@ViewBag.app_version" rel="stylesheet" />
    <link href="~/assets/site/site.css?v=@ViewBag.app_version" rel="stylesheet" />
}
@section scripts{
    <script src="~/assets/app/initialize.js?v=@ViewBag.app_version"></script>
    <script src="~/assets/site/instructor/edit.js?v=@ViewBag.app_version"></script>
}

ElearningApp/Views/Instructor/Index.cshtml
@{
    ViewBag.title = "Instructor";
    ViewBag.app_version = ElearningApp.Models.Helpers.APP_VERSION;
}
<div class="material-background ms-hero-img-elearning ms-hero-bg-app"></div>
<div class="container container-full app-container">
    <div class="app-container-breadcrumb app-has-ms-paper-menu">
        <ul class="app-breadcrumb animated fadeInRight animation-delay-5">
            <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"> </span></a></li>
            <li><a href="javascript:void(0)" class="active">Instructor</a></li>
        </ul>
    </div>
    <div class="ms-paper">
        <div class="row">
            <div class="col-12 ms-paper-content-container">
                <div class="ms-paper-content">
                    <div class="app-row mb-5">
                        <h1 class="pull-left m-0">Instructor</h1>
                        <div class="pull-right">
                            @Helpers.TagHelper.buttonNew(@Url.Action("Create", "Instructor"))
                        </div>
                    </div>
                    <div class="app-form">
                        <table id="instructor_index_table" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th class="align-middle text-ws-normal">Documento</th>
                                    <th class="align-middle text-ws-normal">Nombre</th>
                                    <th class="align-middle text-ws-normal">Email</th>
                                    <th class="align-middle text-ws-normal">Tipo</th>
                                    <th class="align-middle text-ws-normal">Estado</th>
                                    <th class="align-middle text-ws-normal">Acciones</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section styles{
    <link href="~/bower_components/DataTables/datatables.min.css" rel="stylesheet" />
    <link href="~/bower_components/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/bower_components/jquery.scrollbar/jquery.scrollbar.css" rel="stylesheet" />
    <link href="~/assets/app/app.css?v=@ViewBag.app_version" rel="stylesheet" />
    <link href="~/assets/site/site.css?v=@ViewBag.app_version" rel="stylesheet" />
}
@section scripts{
    <script src="~/bower_components/DataTables/datatables.min.js"></script>
    <script src="~/bower_components/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/bower_components/jquery.scrollbar/jquery.scrollbar.min.js"></script>
    <script src="~/assets/app/initialize.js?v=@ViewBag.app_version"></script>
    <script src="~/assets/site/instructor/index.js?v=@ViewBag.app_version"></script>
}

ElearningApp/Views/Instructor/NotFound.cshtml
@{
    ViewBag.title = "Instructor no encontrado";
}
<div class="material-background ms-hero-img-elearning ms-hero-bg-app"></div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-md-offset-2">
            <div class="card animated fadeInUp animation-delay-7 color-primary withripple">
                <div class="card-body-big color-dark">
                    <div class="text-center">
                        <h1 class="color-primary">Error</h1>
                        <h2>Instructor no encontrado</h2>
                        <p class="lead lead-sm">
                            No hemos encontrado lo que estás buscando.
                        </p>
                        <a href="@Url.Action("Index", "Instructor")" class="btn btn-primary btn-raised">
                            <i class="zmdi zmdi-home"></i> Go Instructor List
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>