ElearningApp/Controllers/SliderController.cs
using ElearningApp.Models.Business;
using ElearningApp.Models.Entity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElearningApp.Filters;
using ElearningApp.Models;
using Microsoft.WindowsAzure.Storage.Blob;

namespace ElearningApp.Controllers
{
    [AppAuthenticate]
    public class SliderController : Controller
    {
        // GET: Slider
        [AppAuthorize]
        [AppLog]
        public ActionResult Index()
        {
            ViewBag.NGon.token_access = Helpers.LoginApiEleaLms();
            ViewBag.NGon.username = SessionHelpers.GetUsername();
            ViewBag.NGon.ipaddress = SessionHelpers.GetIPAddress();
            ViewBag.NGon.UrlApi_slider_listAll = System.Configuration.ConfigurationManager.AppSettings["UrlApi_slider_listAll"];
            ViewBag.NGon.UrlApi_slider_delete = System.Configuration.ConfigurationManager.AppSettings["UrlApi_slider_delete"];
            ViewBag.NGon.UrlApi_slider_updStatus = System.Configuration.ConfigurationManager.AppSettings["UrlApi_slider_updStatus"];
            return View();
        }

        // GET: Slider
        [AppAuthorize]
        [AppLog]
        public ActionResult Add()
        {
            ViewBag.NGon.token_access = Helpers.LoginApiEleaLms();
            ViewBag.NGon.username = SessionHelpers.GetUsername();
            ViewBag.NGon.ipaddress = SessionHelpers.GetIPAddress();
            ViewBag.NGon.UrlApi_slider_saveUpd = System.Configuration.ConfigurationManager.AppSettings["UrlApi_slider_saveUpd"];
            return View();
        }

        // GET: Slider
        [AppAuthorize]
        [AppLog]
        public ActionResult Edit(string id)
        {
            ViewBag.NGon.token_access = Helpers.LoginApiEleaLms();
            ViewBag.NGon.username = SessionHelpers.GetUsername();
            ViewBag.NGon.ipaddress = SessionHelpers.GetIPAddress();
            ViewBag.NGon.UrlApi_slider_id = System.Configuration.ConfigurationManager.AppSettings["UrlApi_slider_id"];
            ViewBag.NGon.UrlApi_slider_saveUpd = System.Configuration.ConfigurationManager.AppSettings["UrlApi_slider_saveUpd"];
            ViewBag.NGon.Codi_Sldr = id;
            return View();
        }
    }
}

ElearningApp/Views/Slider/Add.cshtml
@{
    ViewBag.title = "Slider :: Nuevo";
    ViewBag.app_version = ElearningApp.Models.Helpers.APP_VERSION;
}
@using NGon
@Html.IncludeNGon()
<div class="material-background ms-hero-img-elearning ms-hero-bg-app"></div>
<div class="container container-full app-container">
    <div class="app-container-breadcrumb">
        <ul class="app-breadcrumb animated fadeInRight animation-delay-5">
            <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"> </span></a></li>
            <li><a href="@Url.Action("Index", "Slider")">Slider</a></li>
            <li><a href="javascript:void(0)" class="active">Nuevo</a></li>
        </ul>
    </div>
    <div class="card animated slideInUp animation-delay-8">
        <div class="card-body">
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane fade active show" id="generaldata">
                    <form id="slider_create_form" autocomplete="off" action="#" class="app-form" data-presave-rule="object" data-presave-analysis="insert">
                        <div class="row">
                            <div class="col-12 col-sm-10">
                                <div class="form-group mt-0">
                                    <label class="control-label" for="slider_create_name"><span class="text-dark">Título</span> <span class="text-danger">*</span> | Máximo 200 caracteres</label>
                                    <input id="slider_create_name" type="text" maxlength="200" class="form-control" data-presave-object="Título" />
                                </div>
                            </div>
                            <div class="col-12 col-sm-2">
                                <div class="form-group mt-0">
                                    <label class="control-label" for="slider_create_status"><span class="text-dark">Visible</span></label>
                                    <div class="togglebutton">
                                        <label>
                                            <input id="slider_create_status" type="checkbox" checked>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 col-sm-6">
                                <div class="form-group mt-0">
                                    <label class="control-label"><span class="text-dark">Descripción</span> <span class="text-danger">*</span></label>
                                    <div id="slider_create_descripcion"></div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="form-group mt-0">
                                    <label class="control-label" for="slider_create_image"><span class="text-dark">Imagen</span> <span class="text-danger">*</span></label>
                                    <input id="slider_create_image_display" type="text" readonly class="form-control" placeholder="Seleccionar..." data-presave-object="Imagen" />
                                    <input id="slider_create_image" type="file" title=" " />
                                </div>
                                <figure class="ms-thumbnail ms-thumbnail-diagonal card cls-1810071216">
                                    <img id="slider_create_image_preview" src="~/assets/app/img/no-image-icon.svg" alt="" class="img-fluid cls-1810071157" />
                                    <figcaption class="ms-thumbnail-caption text-center">
                                        <div class="ms-thumbnail-caption-content">
                                            <h3 id="slider_create_image_notification" class="ms-thumbnail-caption-title">Ninguna imagen seleccionada</h3>
                                            <div class="mt-2">
                                                <a id="slider_create_image_btn_add" href="javascript:void(0)" class="btn-circle btn-circle-raised btn-circle-sm mr-1 btn-circle-white color-primary">
                                                    <i class="zmdi zmdi-plus"></i>
                                                </a>
                                                <a id="slider_create_image_btn_remove" href="javascript:void(0)" class="btn-circle btn-circle-raised btn-circle-sm mr-1 btn-circle-white color-danger" style="display: none;">
                                                    <i class="zmdi zmdi-close"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </figcaption>
                                </figure>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <hr class="border-dark" />
            <div class="app-row mt-2">
                <span class="small text-dark">Campo requerido (<span class="text-danger">*</span>)</span>
                @Helpers.TagHelper.buttonSave("slider_create_save")
            </div>
        </div>
    </div>
</div>
@section styles{
    <link href="~/bower_components/summernote/summernote.css" rel="stylesheet" />
    <link href="~/bower_components/DataTables/datatables.min.css" rel="stylesheet" />
    <link href="~/bower_components/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/bower_components/jquery.scrollbar/jquery.scrollbar.css" rel="stylesheet" />
    <link href="~/assets/app/app.css?v=@ViewBag.app_version" rel="stylesheet" />
    <link href="~/assets/site/site.css?v=@ViewBag.app_version" rel="stylesheet" />
}
@section scripts{
    <script src="~/bower_components/summernote/summernote.js"></script>
    <script src="~/bower_components/summernote/lang/summernote-es-ES.js"></script>
    <script src="~/bower_components/DataTables/datatables.min.js"></script>
    <script src="~/bower_components/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/bower_components/jquery.scrollbar/jquery.scrollbar.min.js"></script>
    <script src="~/assets/app/initialize.js?v=@ViewBag.app_version"></script>
    <script src="~/assets/site/slider/add.js?v=@ViewBag.app_version"></script>
}

ElearningApp/Views/Slider/Edit.cshtml
@{
    ViewBag.title = "Slider :: Edit";
    ViewBag.app_version = ElearningApp.Models.Helpers.APP_VERSION;
}
@using NGon
@Html.IncludeNGon()
<div class="material-background ms-hero-img-elearning ms-hero-bg-app"></div>
<div class="container container-full app-container">
    <div class="app-container-breadcrumb">
        <ul class="app-breadcrumb animated fadeInRight animation-delay-5">
            <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"> </span></a></li>
            <li><a href="@Url.Action("Index", "Slider")">Slider</a></li>
            <li><a href="javascript:void(0)" class="active">Editar</a></li>
        </ul>
    </div>
    <div class="card animated slideInUp animation-delay-8">
        <div class="card-body">
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane fade active show" id="generaldata">
                    <form id="slider_create_form" autocomplete="off" action="#" class="app-form" data-presave-rule="object" data-presave-analysis="insert">
                        <div class="row">
                            <div class="col-12 col-sm-10">
                                <div class="form-group mt-0">
                                    <label class="control-label" for="slider_create_name"><span class="text-dark">Título</span> <span class="text-danger">*</span> | Máximo 200 caracteres</label>
                                    <input id="slider_create_name" type="text" maxlength="200" class="form-control" data-presave-object="Título" />
                                </div>
                            </div>
                            <div class="col-12 col-sm-2">
                                <div class="form-group mt-0">
                                    <label class="control-label" for="slider_create_status"><span class="text-dark">Visible</span></label>
                                    <div class="togglebutton">
                                        <label>
                                            <input id="slider_create_status" type="checkbox" checked>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 col-sm-6">
                                <div class="form-group mt-0">
                                    <label class="control-label"><span class="text-dark">Descripción</span> <span class="text-danger">*</span></label>
                                    <div id="slider_create_descripcion"></div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="form-group mt-0">
                                    <label class="control-label" for="slider_create_image"><span class="text-dark">Imagen</span> <span class="text-danger">*</span></label>
                                    <input id="slider_create_image_display" type="text" readonly class="form-control" placeholder="Seleccionar..." data-presave-object="Imagen" />
                                    <input id="slider_create_image" type="file" title=" " />
                                </div>
                                <figure class="ms-thumbnail ms-thumbnail-diagonal card cls-1810071216">
                                    <img id="slider_create_image_preview" src="~/assets/app/img/no-image-icon.svg" alt="" class="img-fluid cls-1810071157" />
                                    <figcaption class="ms-thumbnail-caption text-center">
                                        <div class="ms-thumbnail-caption-content">
                                            <h3 id="slider_create_image_notification" class="ms-thumbnail-caption-title">Ninguna imagen seleccionada</h3>
                                            <div class="mt-2">
                                                <a id="slider_create_image_btn_add" href="javascript:void(0)" class="btn-circle btn-circle-raised btn-circle-sm mr-1 btn-circle-white color-primary">
                                                    <i class="zmdi zmdi-plus"></i>
                                                </a>
                                                <a id="slider_create_image_btn_remove" href="javascript:void(0)" class="btn-circle btn-circle-raised btn-circle-sm mr-1 btn-circle-white color-danger" style="display: none;">
                                                    <i class="zmdi zmdi-close"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </figcaption>
                                </figure>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <hr class="border-dark" />
            <div class="app-row mt-2">
                <span class="small text-dark">Campo requerido (<span class="text-danger">*</span>)</span>
                @Helpers.TagHelper.buttonSave("slider_create_save")
            </div>
        </div>
    </div>
</div>
@section styles{
    <link href="~/bower_components/summernote/summernote.css" rel="stylesheet" />
    <link href="~/bower_components/DataTables/datatables.min.css" rel="stylesheet" />
    <link href="~/bower_components/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/bower_components/jquery.scrollbar/jquery.scrollbar.css" rel="stylesheet" />
    <link href="~/assets/app/app.css?v=@ViewBag.app_version" rel="stylesheet" />
    <link href="~/assets/site/site.css?v=@ViewBag.app_version" rel="stylesheet" />
}
@section scripts{
    <script src="~/bower_components/summernote/summernote.js"></script>
    <script src="~/bower_components/summernote/lang/summernote-es-ES.js"></script>
    <script src="~/bower_components/DataTables/datatables.min.js"></script>
    <script src="~/bower_components/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/bower_components/jquery.scrollbar/jquery.scrollbar.min.js"></script>
    <script src="~/assets/app/initialize.js?v=@ViewBag.app_version"></script>
    <script src="~/assets/site/slider/edit.js?v=@ViewBag.app_version"></script>
}

ElearningApp/Views/Slider/Index.cshtml
@{
    ViewBag.Title = "Slider";
    ViewBag.app_version = ElearningApp.Models.Helpers.APP_VERSION;
}
@using NGon
@Html.IncludeNGon()
<div class="material-background ms-hero-img-elearning ms-hero-bg-app"></div>
<div class="container container-full app-container">
    <div class="app-container-breadcrumb app-has-ms-paper-menu">
        <ul class="app-breadcrumb animated fadeInRight animation-delay-5">
            <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"> </span></a></li>
            <li><a href="javascript:void(0)" class="active">Slider</a></li>
        </ul>
    </div>
    <div class="ms-paper">
        <div class="row">
            <div class="col-12 ms-paper-content-container">
                <div class="ms-paper-content">
                    <div class="app-row mb-5">
                        <h1 class="pull-left m-0">Slider</h1>
                        <div class="pull-right">
                            @Helpers.TagHelper.buttonNew(@Url.Action("Add", "Slider"))
                        </div>
                    </div>
                    @*<div class="app-row cls-1902151559">
                            <div id="category_index_buttons" class="pull-left"></div>
                        </div>*@
                    <div class="app-form">
                        <table id="slider_index_table" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th class="align-middle text-ws-normal text-center">Título</th>
                                    <th class="align-middle text-ws-normal text-center">Descripción</th>
                                    <th class="align-middle text-ws-normal text-center">Imagen</th>
                                    <th class="align-middle text-ws-normal text-center">Visible</th>
                                    <th class="align-middle text-ws-normal text-center">Acciones</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section styles{
    <link href="~/bower_components/DataTables/datatables.min.css" rel="stylesheet" />
    <link href="~/bower_components/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/bower_components/jquery.scrollbar/jquery.scrollbar.css" rel="stylesheet" />
    <link href="~/assets/app/app.css?v=@ViewBag.app_version" rel="stylesheet" />
    <link href="~/assets/site/site.css?v=@ViewBag.app_version" rel="stylesheet" />
}
@section scripts{
    <script src="~/bower_components/DataTables/datatables.min.js"></script>
    <script src="~/bower_components/DataTables/Buttons-1.5.4/js/dataTables.buttons.min.js"></script>
    <script src="~/bower_components/DataTables/Buttons-1.5.4/js/buttons.html5.min.js"></script>
    <script src="~/bower_components/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/bower_components/jquery.scrollbar/jquery.scrollbar.min.js"></script>
    <script src="~/assets/app/initialize.js?v=@ViewBag.app_version"></script>
    <script src="~/assets/site/slider/index.js?v=@ViewBag.app_version"></script>
}