ElearningApp/Controllers/DocumentController.cs
using ElearningApp.Filters;
using ElearningApp.Models;
using ElearningApp.Models.Business;
using ElearningApp.Models.Entity;
using Microsoft.WindowsAzure.Storage.Blob;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElearningApp.Controllers
{
    [AppAuthenticate]
    public class DocumentController : Controller
    {
        // GET: Document
        [AppAuthorize]
        [AppLog]
        public ActionResult Index()
        {
            return View();
        }
        [AppAuthorize]
        [AppLog]
        public ActionResult Create()
        {
            return View();
        }
        [AppAuthorize]
        [AppLog]
        public ActionResult Edit(string id)
        {
            int l_id = Convert.ToInt32(Helpers.GetBase64Decode(id));
            Bus_List l_list = new Bus_List();
            Document_Entity l_model = null;
            var l_document = l_list.RetrieveDocument(l_id);
            bool l_noData = l_document.Rows.Count == 0;
            if (!l_noData)
            {
                l_model = new Document_Entity
                {
                    Id = l_id,
                    Description = Convert.ToString(l_document.Rows[0]["Descripcion"]),
                    ShortDescription = Convert.ToString(l_document.Rows[0]["Descripcion_Corta"]),
                    Type = Convert.ToString(l_document.Rows[0]["Tipo"]),
                    Model = new File_Entity
                    {
                        Name = Convert.ToString(l_document.Rows[0]["Modelo"])
                    },
                    Order = Convert.ToDecimal(l_document.Rows[0]["Orden"]),
                    HasNumber = Convert.ToString(l_document.Rows[0]["Flag_Numeracion"]),
                    HasDates = Convert.ToString(l_document.Rows[0]["Flag_Fecha"]),
                    HasMassive = Convert.ToString(l_document.Rows[0]["Flag_Masivo"]),
                    HasLogistica = Convert.ToString(l_document.Rows[0]["Flag_Logistica"]),
                    Status = Convert.ToString(l_document.Rows[0]["Estado"])
                };
            }

            Helpers.ClearDataTable(l_document);
            l_list = null;

            ViewBag.NGon.Model = l_model;

            if (l_noData)
            {
                return View("NotFound");
            }
            else
            {
                return View(l_model);
            }
        }
        [HttpPost]
        public ActionResult Create(Document_Entity p_Entity)
        {
            Bus_Crud l_crud;
            AzureStorageHelpers l_storage = null;
            DataTable l_dt = null;
            try
            {
                l_crud = new Bus_Crud();
                l_storage = new AzureStorageHelpers("Azure_ContainerName_Administracion_Proveedor", BlobContainerPublicAccessType.Blob, "Azure_AccountName_Administracion", "Azure_AccessKey_Administracion");
                //save model
                if (p_Entity.Model.File != null)
                {
                    p_Entity.Model.Name = DateTime.Now.ToString("ddMMyyyyHHmmssffffff") + "-" + p_Entity.Model.File.FileName;
                    p_Entity.Model.Properties = "{\"Type\":\"" + Convert.ToString(p_Entity.Model.File.ContentType) + "\",\"Length\":" + Convert.ToString(p_Entity.Model.File.ContentLength) + "}";
                    //upload to storage
                    l_storage.UploadBlob(Helpers.DIRECTORY_DOCUMENT_MODEL
                        .Replace("{filename}", p_Entity.Model.Name), p_Entity.Model.File.InputStream);
                    p_Entity.Model.Uploaded = true;
                }
                //save in db
                p_Entity.Username = SessionHelpers.GetUsername();
                p_Entity.IPAddress = SessionHelpers.GetIPAddress();
                l_dt = l_crud.InsertUpdateDocument(p_Entity);
                if (l_dt.Rows[0]["Value"].ToString() != "1000")
                {
                    try
                    {
                        if (p_Entity.Model.Uploaded)
                        {
                            l_storage.DeleteBlob(Helpers.DIRECTORY_DOCUMENT_MODEL
                                .Replace("{filename}", p_Entity.Model.Name));
                        }
                    }
                    catch
                    {
                        //prevent
                    }
                }
                return Helpers.GetMessageCrud(l_dt);
            }
            catch (Exception e)
            {
                if (l_storage != null)
                {
                    try
                    {
                        if (p_Entity.Model.Uploaded)
                        {
                            l_storage.DeleteBlob(Helpers.DIRECTORY_DOCUMENT_MODEL
                                .Replace("{filename}", p_Entity.Model.Name));
                        }
                    }
                    catch
                    {
                        //prevent
                    }
                }
                return Helpers.GetException(e);
            }
            finally
            {
                l_crud = null;
                if (l_storage != null)
                {
                    l_storage.Clear();
                    l_storage = null;
                }
                Helpers.ClearDataTable(l_dt);
            }
        }
        [HttpPost]
        public ActionResult Edit(Document_Entity p_Entity)
        {
            Bus_Crud l_crud;
            AzureStorageHelpers l_storage = null;
            DataTable l_dt = null;
            try
            {
                l_crud = new Bus_Crud();
                l_storage = new AzureStorageHelpers("Azure_ContainerName_Administracion_Proveedor", BlobContainerPublicAccessType.Blob, "Azure_AccountName_Administracion", "Azure_AccessKey_Administracion");
                //save model
                if (p_Entity.Model.File != null)
                {
                    p_Entity.Model.Name = DateTime.Now.ToString("ddMMyyyyHHmmssffffff") + "-" + p_Entity.Model.File.FileName;
                    p_Entity.Model.Properties = "{\"Type\":\"" + Convert.ToString(p_Entity.Model.File.ContentType) + "\",\"Length\":" + Convert.ToString(p_Entity.Model.File.ContentLength) + "}";
                    //upload to storage
                    l_storage.UploadBlob(Helpers.DIRECTORY_DOCUMENT_MODEL
                        .Replace("{filename}", p_Entity.Model.Name), p_Entity.Model.File.InputStream);
                    p_Entity.Model.Uploaded = true;
                }
                //save in db
                p_Entity.Username = SessionHelpers.GetUsername();
                p_Entity.IPAddress = SessionHelpers.GetIPAddress();
                l_dt = l_crud.InsertUpdateDocument(p_Entity);
                if (l_dt.Rows[0]["Value"].ToString() == "1000")
                {
                    try
                    {
                        if (p_Entity.Model.Name != p_Entity.Model.OldName)
                        {
                            l_storage.DeleteBlob(Helpers.DIRECTORY_DOCUMENT_MODEL
                                .Replace("{filename}", p_Entity.Model.OldName));
                        }
                    }
                    catch
                    {
                        //prevent
                    }
                }
                else
                {
                    try
                    {
                        if (p_Entity.Model.Uploaded)
                        {
                            l_storage.DeleteBlob(Helpers.DIRECTORY_DOCUMENT_MODEL
                                .Replace("{filename}", p_Entity.Model.Name));
                        }
                    }
                    catch
                    {
                        //prevent
                    }
                }
                return Helpers.GetMessageCrud(l_dt);
            }
            catch (Exception e)
            {
                if (l_storage != null)
                {
                    try
                    {
                        if (p_Entity.Model.Uploaded)
                        {
                            l_storage.DeleteBlob(Helpers.DIRECTORY_DOCUMENT_MODEL
                                .Replace("{filename}", p_Entity.Model.Name));
                        }
                    }
                    catch
                    {
                        //prevent
                    }
                }
                return Helpers.GetException(e);
            }
            finally
            {
                l_crud = null;
                if (l_storage != null)
                {
                    l_storage.Clear();
                    l_storage = null;
                }
                Helpers.ClearDataTable(l_dt);
            }
        }
        [HttpPost]
        public ActionResult Delete(Document_Entity p_Entity)
        {
            Bus_Crud l_crud;
            Bus_List l_list;
            AzureStorageHelpers l_storage = null;
            try
            {
                l_crud = new Bus_Crud();
                l_list = new Bus_List();
                p_Entity.Username = SessionHelpers.GetUsername();
                p_Entity.IPAddress = SessionHelpers.GetIPAddress();
                var l_document = l_list.RetrieveDocument(Convert.ToInt32(p_Entity.Id));
                var l_response = l_crud.DeleteDocument(p_Entity);
                if (l_response.Rows[0]["Value"].ToString() == "1000")
                {
                    l_storage = new AzureStorageHelpers("Azure_ContainerName_Administracion_Proveedor", BlobContainerPublicAccessType.Blob, "Azure_AccountName_Administracion", "Azure_AccessKey_Administracion");
                    try
                    {
                        if (l_document.Rows[0]["Modelo"].ToString() != "")
                        {
                            l_storage.DeleteBlob(Helpers.DIRECTORY_DOCUMENT_MODEL

ElearningApp/Views/Document/Create.cshtml
@{
    ViewBag.title = "Documento :: Nuevo";
    ViewBag.app_version = ElearningApp.Models.Helpers.APP_VERSION;
}
<div class="material-background ms-hero-img-elearning ms-hero-bg-app"></div>
<div class="container container-full app-container">
    <div class="app-container-breadcrumb">
        <ul class="app-breadcrumb animated fadeInRight animation-delay-5">
            <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"> </span></a></li>
            <li><a href="@Url.Action("Index", "Document")">Documento</a></li>
            <li><a href="javascript:void(0)" class="active">Nuevo</a></li>
        </ul>
    </div>
    <div class="card animated slideInUp animation-delay-8">
        <div class="card-body">
            <form id="document_create_form" autocomplete="off" action="#" class="app-form" data-presave-rule="object" data-presave-analysis="insert">
                <div class="row">
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_create_description"><span class="text-dark">Descripción</span> <span class="text-danger">*</span> | Máximo 200 caracteres</label>
                            <input id="document_create_description" type="text" maxlength="200" class="form-control" data-presave-object="Descripción" />
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_create_short_description"><span class="text-dark">Descripción Corta</span> <span class="text-danger">*</span> | Máximo 20 caracteres</label>
                            <input id="document_create_short_description" type="text" maxlength="20" class="form-control" data-presave-object="Descripción Corta" />
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_create_type"><span class="text-dark">Tipo</span> <span class="text-danger">*</span></label>
                            <select id="document_create_type" class="form-control" data-live-search="true" data-dropup-auto="false" data-presave-object="Tipo">
                                <option value="P">Empresa</option>
                                <option value="T">Trabajador</option>
                                <option value="U">Vehículo</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-8">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_create_model"><span class="text-dark">Modelo</span></label>
                            <div class="app-row">
                                <div class="pull-left cls-1905021145">
                                    <input id="document_create_model_display" type="text" readonly class="form-control" placeholder="Seleccionar..." data-presave-object="Modelo" />
                                    <input id="document_create_model" type="file" title=" " />
                                </div>
                                <div class="pull-right cls-1905021146">
                                    <button id="document_create_btn_clear_model" class="btn btn-raised btn-warning m-0" type="button" data-toggle="tooltip" data-placement="top" title="Limpiar">
                                        <i class="glyphicon glyphicon-erase m-0"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_create_order"><span class="text-dark">Orden</span> <span class="text-danger">*</span> | Número entero no menor a uno</label>
                            <input id="document_create_order" type="number" min="0" class="form-control" data-presave-object="Orden" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-3 col-sm-2">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_create_has_number"><span class="text-dark">Numeración</span></label>
                            <div class="togglebutton">
                                <label>
                                    <input id="document_create_has_number" type="checkbox" />
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-3 col-sm-2">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_create_has_dates"><span class="text-dark">Fechas</span></label>
                            <div class="togglebutton">
                                <label>
                                    <input id="document_create_has_dates" type="checkbox" />
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-3 col-sm-2">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_create_has_massive"><span class="text-dark">Masivo</span></label>
                            <div class="togglebutton">
                                <label>
                                    <input id="document_create_has_massive" type="checkbox" />
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-3 col-sm-2">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_create_has_logistica"><span class="text-dark">Logística</span></label>
                            <div class="togglebutton">
                                <label>
                                    <input id="document_create_has_logistica" type="checkbox" />
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_create_status"><span class="text-dark">Activo</span></label>
                            <div class="togglebutton">
                                <label>
                                    <input id="document_create_status" type="checkbox" checked />
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <hr class="border-dark" />
            <div class="app-row">
                <span class="small text-dark">Campo requerido (<span class="text-danger">*</span>)</span>
                @Helpers.TagHelper.buttonSave("document_create_save")
            </div>
        </div>
    </div>
</div>
@section styles{
    <link href="~/assets/app/app.css?v=@ViewBag.app_version" rel="stylesheet" />
    <link href="~/assets/site/site.css?v=@ViewBag.app_version" rel="stylesheet" />
}
@section scripts{
    <script src="~/assets/app/initialize.js?v=@ViewBag.app_version"></script>
    <script src="~/assets/site/document/create.js?v=@ViewBag.app_version"></script>
}

ElearningApp/Views/Document/Edit.cshtml
@model ElearningApp.Models.Entity.Document_Entity
@{
    ViewBag.title = "Documento :: Editar";
    ViewBag.app_version = ElearningApp.Models.Helpers.APP_VERSION;
}
@using NGon
@Html.IncludeNGon()
<div class="material-background ms-hero-img-elearning ms-hero-bg-app"></div>
<div class="container container-full app-container">
    <div class="app-container-breadcrumb">
        <ul class="app-breadcrumb animated fadeInRight animation-delay-5">
            <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"> </span></a></li>
            <li><a href="@Url.Action("Index", "Document")">Documento</a></li>
            <li><a href="javascript:void(0)" class="active">Editar</a></li>
        </ul>
    </div>
    <div class="card animated slideInUp animation-delay-8">
        <div class="card-body">
            <form id="document_edit_form" autocomplete="off" action="#" class="app-form" data-presave-rule="object" data-presave-analysis="insert">
                <div class="row">
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_edit_description"><span class="text-dark">Descripción</span> <span class="text-danger">*</span> | Máximo 200 caracteres</label>
                            <input id="document_edit_description" type="text" maxlength="200" class="form-control" data-presave-object="Descripción" value="@Model.Description" />
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_edit_short_description"><span class="text-dark">Descripción Corta</span> <span class="text-danger">*</span> | Máximo 20 caracteres</label>
                            <input id="document_edit_short_description" type="text" maxlength="20" class="form-control" data-presave-object="Descripción Corta" value="@Model.ShortDescription" />
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_edit_type"><span class="text-dark">Tipo</span> <span class="text-danger">*</span></label>
                            <select id="document_edit_type" class="form-control" data-live-search="true" data-dropup-auto="false" data-presave-object="Tipo">
                                <option value="P">Empresa</option>
                                <option value="T">Trabajador</option>
                                <option value="U">Vehículo</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm-8">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_edit_model"><span class="text-dark">Modelo</span></label>
                            <div class="app-row">
                                <div class="pull-left cls-1905021145">
                                    <input id="document_edit_model_display" type="text" readonly class="form-control" placeholder="Seleccionar..." data-presave-object="Modelo" value="@Model.Model.Name" />
                                    <input id="document_edit_model" type="file" title=" " />
                                </div>
                                <div class="pull-right cls-1905021146">
                                    <button id="document_edit_btn_clear_model" class="btn btn-raised btn-warning m-0" type="button" data-toggle="tooltip" data-placement="top" title="Limpiar">
                                        <i class="glyphicon glyphicon-erase m-0"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_edit_order"><span class="text-dark">Orden</span> <span class="text-danger">*</span> | Número entero no menor a uno</label>
                            <input id="document_edit_order" type="number" min="0" class="form-control" data-presave-object="Orden" value="@Model.Order" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-3 col-sm-2">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_edit_has_number"><span class="text-dark">Numeración</span></label>
                            <div class="togglebutton">
                                <label>
                                    <input id="document_edit_has_number" type="checkbox" @(Model.HasNumber == "S" ? "checked" : "") />
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-3 col-sm-2">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_edit_has_dates"><span class="text-dark">Fechas</span></label>
                            <div class="togglebutton">
                                <label>
                                    <input id="document_edit_has_dates" type="checkbox" @(Model.HasDates == "S" ? "checked" : "") />
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-3 col-sm-2">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_edit_has_massive"><span class="text-dark">Masivo</span></label>
                            <div class="togglebutton">
                                <label>
                                    <input id="document_edit_has_massive" type="checkbox" @(Model.HasMassive == "S" ? "checked" : "") />
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-3 col-sm-2">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_edit_has_logistica"><span class="text-dark">Logística</span></label>
                            <div class="togglebutton">
                                <label>
                                    <input id="document_edit_has_logistica" type="checkbox" @(Model.HasLogistica == "S" ? "checked" : "") />
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group mt-0">
                            <label class="control-label" for="document_edit_status"><span class="text-dark">Activo</span></label>
                            <div class="togglebutton">
                                <label>
                                    <input id="document_edit_status" type="checkbox" @(Model.Status == "A" ? "checked" : "") />
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <hr class="border-dark" />
            <div class="app-row">
                <span class="small text-dark">Campo requerido (<span class="text-danger">*</span>)</span>
                @Helpers.TagHelper.buttonSave("document_edit_save")
            </div>
        </div>
    </div>
</div>
@section styles{
    <link href="~/assets/app/app.css?v=@ViewBag.app_version" rel="stylesheet" />
    <link href="~/assets/site/site.css?v=@ViewBag.app_version" rel="stylesheet" />
}
@section scripts{
    <script src="~/assets/app/initialize.js?v=@ViewBag.app_version"></script>
    <script src="~/assets/site/document/edit.js?v=@ViewBag.app_version"></script>
}

ElearningApp/Views/Document/Index.cshtml
@{
    ViewBag.title = "Documento";
    ViewBag.app_version = ElearningApp.Models.Helpers.APP_VERSION;
}
<div class="material-background ms-hero-img-elearning ms-hero-bg-app"></div>
<div class="container container-full app-container">
    <div class="app-container-breadcrumb app-has-ms-paper-menu">
        <ul class="app-breadcrumb animated fadeInRight animation-delay-5">
            <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"> </span></a></li>
            <li><a href="javascript:void(0)" class="active">Documento</a></li>
        </ul>
    </div>
    <div class="ms-paper">
        <div class="row">
            <div class="col-12 ms-paper-content-container">
                <div class="ms-paper-content">
                    <div class="app-row mb-5">
                        <h1 class="pull-left m-0">Documento</h1>
                        <div class="pull-right">
                            @Helpers.TagHelper.buttonNew(Url.Action("Create", "Document"))
                        </div>
                    </div>
                    <div class="app-form">
                        <table id="document_index_table" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th class="align-middle text-ws-normal text-center">Descripción</th>
                                    <th class="align-middle text-ws-normal text-center">Tipo</th>
                                    <th class="align-middle text-ws-normal text-center">Fecha</th>
                                    <th class="align-middle text-ws-normal text-center">Numeración</th>
                                    <th class="align-middle text-ws-normal text-center">Masivo</th>
                                    <th class="align-middle text-ws-normal text-center">Orden</th>
                                    <th class="align-middle text-ws-normal text-center">Estado</th>
                                    <th class="align-middle text-ws-normal text-center">Acciones</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section styles{
    <link href="~/bower_components/DataTables/datatables.min.css" rel="stylesheet" />
    <link href="~/bower_components/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/bower_components/jquery.scrollbar/jquery.scrollbar.css" rel="stylesheet" />
    <link href="~/assets/app/app.css?v=@ViewBag.app_version" rel="stylesheet" />
    <link href="~/assets/site/site.css?v=@ViewBag.app_version" rel="stylesheet" />
}
@section scripts{
    <script src="~/bower_components/DataTables/datatables.min.js"></script>
    <script src="~/bower_components/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/bower_components/jquery.scrollbar/jquery.scrollbar.min.js"></script>
    <script src="~/assets/app/initialize.js?v=@ViewBag.app_version"></script>
    <script src="~/assets/site/document/index.js?v=@ViewBag.app_version"></script>
}